### ISSUE TITLE
Draft workshop reviews

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain#1]
Please leave your review comments for our author here.

**Comment by creationsoft** [comment]
Create resource   group and necessary azure resources sections not complete, can't find where to create   the required resources. | microsoft-leveraging-azure-digital-twins-supply-chain/Before   the HOL - Leveraging Azure Digital Twins in a supply chain.md at main ·   solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain   (github.com)
-- | --


**codingbandit: Fixed**

**Comment by codingbandit** [comment]
Ah yes, this will use the ARM template as the existing sample. I missed
returning and making a couple of small adjustments. In the meantime, you
can use the ARM template located here:
https://github.com/Azure-Samples/IoTDemos/tree/master/ADT-SupplyChainDemo#contoso-apparel-developer-version
There is a small adjustment in the deployment linked (the namespace of the
models changed, so the query in the logic app needs changed to
"com.contoso".

I will get this updated today. (EDIT: this has been updated in the current repository)

**Comment by codingbandit** [comment]
@creationsoft - The before the HOL has been updated. Thank you for discovering my omission!!

**Comment by JMayrbaeurl** [comment]
In [Exercise #1 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-the-components-of-a-model) model files are shown starting with an '['. This is wrong and '[' and the closing ']' should be removed.

**codingbandit: Fixed**

**Comment by JMayrbaeurl** [comment]
In [Exercise #1 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-the-components-of-a-model) at:

Let's now continue this exercise by defining a model for a storeroom using DTDL. Feel free to refer to the DTDL specification as a reference.

Let's begin by defining the interface for a storeroom. Open Visual Studio Code to the Hands-on lab/Resources/models folder, and create a new file named storeroom.json. Add the following text to this file:

The 'storeroom.json' file already exists in the downloaded zip file at the specified location. Please remove it.

**codingbandit: Fixed**

**Comment by JMayrbaeurl** [comment]
In [Exercise #1 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-the-components-of-a-model) at:

5.Now we need to add StoreRoom as a relationship in the Factory model. Open the Hands-on lab/Resources/models/factory.json file, and add the following to the contents array:

The relationship is already defined in the 'factory.json' file

**codingbandit: Fixed**

**Comment by JMayrbaeurl** [comment]
In [Exercise #2 Task #2](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-2-loading-models-using-the-cli) at:

8. Upload the storeroom model using the CLI with the following command (replace ADT_INSTANCE_NAME with your Azure Digital Twins instance name):

`az dt model create -n ADT_INSTANCE_NAME --models storeroom.json` is missing the resource group parameter `-g <your_resource_group>`.  Other possibility is to set the default resource group in the default configuration.

Same problem with step 9. following

**codingbandit: Fixed**

**Comment by JMayrbaeurl** [comment]
In [Exercise #5 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-manually-update-the-state-of-a-digital-twin-using-the-cli) at: 

`az dt twin update -n ADT_INSTANCE_NAME --twin-id "SR90636" --json-patch '{"op":"add","path":"/StockLevel","value":42}'`

updating doesn't work. No error shown, but check with azcli or ADT Explorer doesn't show any change. BTW. As always '-g' parameter is missing

Update 2021-04-23: Quoting issue. The correct syntax for Windows Command Prompt looks like:

`az dt twin update -n ADT_INSTANCE_NAME -g RESOURCEGROUP --twin-id "SR90636" --json-patch "{\"op\":\"add\",\"path\":\"/StockLevel\",\"value\":42}"`

**codingbandit**: Thank you for this, also for some reason if you try to do the -g flag before the instance name flag it doesn't update o.O ... this order works though, thank you !!!

**codingbandit: Fixed**

**Comment by JMayrbaeurl** [comment]
In [Exercise #5 Task #3](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-3-using-a-logic-application-to-trigger-azure-digital-twin-updates-for-shipments) at:

Note: If desired, you can choose to execute the Logic app on-demand by selecting Run Trigger from the Overview screen of the service.

Running the trigger fails with 'Unauthorized' in the 'Query QueryTwins' step. Is the described Authorization setup really working?

**codingbandit: Fixed**

**Comment by JMayrbaeurl** [comment]
In [Exercise #6](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#exercise-6-visualizing-incoming-data-with-azure-time-series-insights) no events are routed from ADT to the event hub. Therefore no visualization in TSI

**Comment by codingbandit** [comment]
> In [Exercise #1 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-the-components-of-a-model) model files are shown starting with an '['. This is wrong and '[' and the closing ']' should be removed.

Fixed

**Comment by codingbandit** [comment]
> In [Exercise #1 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-the-components-of-a-model) at:
> 
> Let's now continue this exercise by defining a model for a storeroom using DTDL. Feel free to refer to the DTDL specification as a reference.
> 
> Let's begin by defining the interface for a storeroom. Open Visual Studio Code to the Hands-on lab/Resources/models folder, and create a new file named storeroom.json. Add the following text to this file:
> 
> The 'storeroom.json' file already exists in the downloaded zip file at the specified location. Please remove it.

Fixed

**Comment by codingbandit** [comment]
> In [Exercise #1 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-the-components-of-a-model) at:
> 
> Let's now continue this exercise by defining a model for a storeroom using DTDL. Feel free to refer to the DTDL specification as a reference.
> 
> Let's begin by defining the interface for a storeroom. Open Visual Studio Code to the Hands-on lab/Resources/models folder, and create a new file named storeroom.json. Add the following text to this file:
> 
> The 'storeroom.json' file already exists in the downloaded zip file at the specified location. Please remove it.

Fixed

**Comment by codingbandit** [comment]
> In [Exercise #2 Task #2](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-2-loading-models-using-the-cli) at:
> 
> 1. Upload the storeroom model using the CLI with the following command (replace ADT_INSTANCE_NAME with your Azure Digital Twins instance name):
> 
> `az dt model create -n ADT_INSTANCE_NAME --models storeroom.json` is missing the resource group parameter `-g <your_resource_group>`. Other possibility is to set the default resource group in the default configuration.
> 
> Same problem with step 9. following

Fixed

**Comment by codingbandit** [comment]
> In [Exercise #5 Task #1](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-1-manually-update-the-state-of-a-digital-twin-using-the-cli) at:
> 
> `az dt twin update -n ADT_INSTANCE_NAME --twin-id "SR90636" --json-patch '{"op":"add","path":"/StockLevel","value":42}'`
> 
> updating doesn't work. No error shown, but check with azcli or ADT Explorer doesn't show any change. BTW. As always '-g' parameter is missing

INVESTIGATING

**Comment by codingbandit** [comment]
> In [Exercise #5 Task #3](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-3-using-a-logic-application-to-trigger-azure-digital-twin-updates-for-shipments) at:
> 
> Note: If desired, you can choose to execute the Logic app on-demand by selecting Run Trigger from the Overview screen of the service.
> 
> Running the trigger fails with 'Unauthorized' in the 'Query QueryTwins' step. Is the described Authorization setup really working?

INVESTIGATING

**Comment by katriendg** [comment]
UI display: on the root Readme.md file, the section after this sentence below is shown as a code block and not easily readable.

'Contoso Apparel is looking to implement digital twins to model their existing supply chain environment end-to-end. Their goals are:'

**codingbandit: Fixed**

**Comment by katriendg** [comment]
In ['Before the HOL section](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#before-the-hands-on-lab)', when creating a new empty Resource Group if might be relevant to add a note about which region to choose. Customers should choose a region where ADT is available upfront. We can link to https://azure.microsoft.com/en-us/global-infrastructure/services/

**codingbandit: Fixed**

**Comment by katriendg** [comment]
INFO: [Before the HOL section](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#before-the-hands-on-lab), the time required (Duration) for me to complete the RG + ARM deployment was about 25 minutes

**codingbandit: Fixed**

**Comment by katriendg** [comment]
HOL -  Task 1 Exercise 1 - point 1 
"Let's begin by defining the interface for a storeroom. Open Visual Studio Code to the Hands-on lab/Resources/models folder, and create a new file named storeroom.json. "
> The file storeroom.json already exists. So either we need to remove the file from the repo or suggest another name. Note that I did a clone of the repo, maybe the ZIP file does have it removed.

**codingbandit: Fixed**

**Comment by katriendg** [comment]
[HOL Task 4](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-4-loading-models-using-the-azure-digital-twins-explorer) - Uploading models fails in ADT Explorer because Storeroom.json is already uploaded.
Change the guide to either make sure the user does not select the latter (and thus only selects 10 json files, or show user to delete the model already in the system before continuing.

**codingbandit: fixed**

**Comment by katriendg** [comment]
[HOL Exercise 2 - Task 3](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-3-importing-digital-twin-instances-using-a-spreadsheet) - importing the graph fails with below message, as the twin ID already exists. Probably best to ask user to either
- create the new twins manually previously with different twin ids
- or ask user to delete the 4 twins created in the exercise above before continuing

![image](https://user-images.githubusercontent.com/838216/115838490-05e60e00-a41a-11eb-93fa-1de9f4f9a070.png)

**codingbandit: fixed**

**Comment by katriendg** [comment]
HOL Exercise 5 - Task 1 - Updating the stock level through CLI returns an error as it seems the double quotes are removed when submitting. Had to escape the quotes for the command to work:

`az dt twin update -g RESOURCE_GROUP_NAME -n ADT_INSTANCE_NAME --twin-id "SR90636" --json-patch '{\"op\":\"add\",\"path\":\"/StockLevel\",\"value\":42}'`

I'm using PowerShell through Windows Terminal.

**codingbandit**: The above syntax didn't update the twin for me, it seems the -n flag MUST come before the -g for the update to take (not sure why this is the case, so I've updated the text with the proper quote escaping and re-ordered -n and -g.

**codingbandit: fixed**

**Comment by katriendg** [comment]
HOL Exercise 5 - Task 3 - Logic App.
The Logic app does not trigger successfully. Within the first call to the API Connection it returns 'Unauthorized'. This is typically linked to the fact that the Authentication through an app registration requires the authorizing user to have more permissions on Azure AD. Previously we used to configure the Azure AD app auth with a API permission and requiring global admin consent.
A workaround to all users in this situation is to leverage MSI, which is supported by Logic Apps but not yet in the API Connection type of connector. I have a write-up of using this option instead, I will mail that to @DawnmarieDesJardins 

**codingbandit: Fixed**

**Comment by katriendg** [comment]
HOL Exercise 6 - Task 1 - Adding permissions. This step is adding Azure AD resource permissions but it should be adding Data plane permissions instead. If I follow the steps in Task 1 I get this error in the TSI explorer:

"Access Denied
You do not have access to environment [...b33d0c..]. You may need to be added via Data Access Policies in the Azure Portal.
"

The correct way to add the TSI data plane permissions is to use the section 'Data Access Policies' instead of 'IAM', and add yourself as Reader and Contributor in one single step. The Step by step is slightly different.

Once the Data Access Policies are configured, I can now access TSI explorer and see the data.

**codingbandit: Fixed**

**Comment by katriendg** [comment]
Whiteboard design session - the file 'WDS trainer presentation - Leveraging Azure Digital Twins in a supply chain.pptx' is an empty template only, no content for this MCW?

**codingbandit: Fixed**

**Comment by Maarten-Work** [comment]
**Student guide and Trainer guide feedback**
1)	Do we use the term *Whiteboard design session* or prefer *Architectural Design Session (ADS)* that is a frequently used term when creating an architecture for a IoT solution?
1)	Typo in [Preferred target audience section](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Whiteboard%20design%20session/WDS%20trainer%20guide%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#preferred-target-audience): Comntoso instead of Contoso
1)	In the trainer guide, *Model updates* and *Data visualization* are mentioned, together with a suggested solution. This is not the case for the *Business logic implementation*, which is only mentioned. This section is just above the [Checklist of preferred objection handling](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Whiteboard%20design%20session/WDS%20trainer%20guide%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#checklist-of-preferred-objection-handling).
1)	In the [Checklist of preferred objection handling](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Whiteboard%20design%20session/WDS%20trainer%20guide%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#checklist-of-preferred-objection-handling), item 3 does not have a suggested answer to the objection to track manufactured products.

**codingbandit: Fixed**

**Comment by Maarten-Work** [comment]
**Before the HOL**

Would be good to have a short overview of the services that will be deployed using the ARM template. Or at least refer to the suggested architecture that was the result of the whiteboarding session. Maybe also an estimate of the subscription costs for the duration of the lab.

**codingbandit: Fixed**

**Comment by Maarten-Work** [comment]
**Exercise 1**

In this exercise, you will be assisting Contoso Apparel in defining a model representing a storeroom. In Contoso's environment, we must track the temperature and humidity telemetry coming storeroom as well as the current stock level.

This should probably be:
In this exercise, you will be assisting Contoso Apparel in defining a model representing a storeroom. In Contoso's environment, we must track the temperature and humidity telemetry coming **from the** storeroom as well as the current stock level.

**codingbandit: Fixed**

**Comment by codingbandit** [comment]
> [HOL Task 4](https://github.com/solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain/blob/main/Hands-on%20lab/HOL%20step-by%20step%20-%20Leveraging%20Azure%20Digital%20Twins%20in%20a%20supply%20chain.md#task-4-loading-models-using-the-azure-digital-twins-explorer) - Uploading models fails in ADT Explorer because Storeroom.json is already uploaded.
> Change the guide to either make sure the user does not select the latter (and thus only selects 10 json files, or show user to delete the model already in the system before continuing.

@katriendg - I understand that storeroom.json was upload previously via CLI, however the Azure Digital Twin Explorer doesn't give me an error (the ADT Explorer just skips it).

**Comment by Maarten-Work** [comment]
**Lab 5 - Task 3 - Logic APP**
Same authorization issues to trigger the logic app as mentioned before.

**codingbandit: Fixed**

**Comment by DawnmarieDesJardins** [comment]
Closing issues as resolved (these were part of SME review).
