### ISSUE TITLE
QC change requests/questions

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [solliancenet/microsoft-leveraging-azure-digital-twins-supply-chain#2]
Hello!  

Here's what I found during QC

**ReadMe Page**
Can we shorten the intro to two paragraphs (no lists or bullets)? Looking for just enough information from the customer situation to make them curious and explore the rest of the workshop.

**Before HOL**
Line 123 - When moved to MS MCW site, link will need to change, correct?
Line 127 - Will image change when we move this to MS?

**Step-by-step HOL**
Lines 262-268 - Need to indented to match the rest of the instructions please. (I have no business touching codes sections, EEK!)

**Trainer Guide**
Preferred solution - The diagram shows a logic app but doesn't mention it in the explanation. Is it obvious to technical people or should it be added to all the docs. with a preferred solution?
Line 456 - Need the "Title" code at the end of the alt-text.
Line 462 - Please update to the alt-text.  It just says **An IoT hub** and no "title" code at the end.

**Student Guide**
Perfect.

**Trainer Presentation (PPT)**
Missing slides after Design the solution slide 8.  Should have slides that tell students what they're supposed be answering (Duplicate the design section of student guide):
- High-level architecture (1 question)
- Environment modeling (4 questions)
- Data ingestion and monitoring (4 questions)
Preferred solution - same question from Trainer guide....do we need to add about the Logic app?

Let me know if anything doesn't make sense.
Dawnmarie

**Comment by timahenning** [comment]
Addressed and merged.
